FROM node:8-alpine

LABEL maintainer="juan.sanchez1192@gmail.com"

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm install --quiet pm2 -g && \
npm install --quiet --only=prod

RUN chown -R node: /usr/src/app

USER node

COPY . ./

CMD ["pm2-docker", "development.json"]
